// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwCc8077k08Rf87xTKtkjzgFG7ZT2niJ8',
    appId: '1:1043891900889:web:9fc154beb54e13274689c8',
    messagingSenderId: '1043891900889',
    projectId: 'fluttertest-8b3de',
    authDomain: 'fluttertest-8b3de.firebaseapp.com',
    storageBucket: 'fluttertest-8b3de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3-euH96SDXALkDZP2BVnH93QrquD1o5c',
    appId: '1:1043891900889:android:717e43e68662c2bd4689c8',
    messagingSenderId: '1043891900889',
    projectId: 'fluttertest-8b3de',
    storageBucket: 'fluttertest-8b3de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6iQyVk60eCfILsAGSCE0n8S1fTwQSr10',
    appId: '1:1043891900889:ios:ce1f4dc5af8d46244689c8',
    messagingSenderId: '1043891900889',
    projectId: 'fluttertest-8b3de',
    storageBucket: 'fluttertest-8b3de.appspot.com',
    iosClientId: '1043891900889-8puu2nhu5qb4pupavpobrftempnifsda.apps.googleusercontent.com',
    iosBundleId: 'com.example.gridUiExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6iQyVk60eCfILsAGSCE0n8S1fTwQSr10',
    appId: '1:1043891900889:ios:ce1f4dc5af8d46244689c8',
    messagingSenderId: '1043891900889',
    projectId: 'fluttertest-8b3de',
    storageBucket: 'fluttertest-8b3de.appspot.com',
    iosClientId: '1043891900889-8puu2nhu5qb4pupavpobrftempnifsda.apps.googleusercontent.com',
    iosBundleId: 'com.example.gridUiExample',
  );
}
