// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU-Ddw3wWGjXx4xU5PIzdELjLY3C5bN9o',
    appId: '1:969353545665:web:6127fdb7de3ab0cb98d140',
    messagingSenderId: '969353545665',
    projectId: 'a18s-app',
    authDomain: 'a18s-app.firebaseapp.com',
    storageBucket: 'a18s-app.appspot.com',
    measurementId: 'G-QK82S2VE5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD3g9KXkdhMXPHnuCJXcxiQOmR-J-q25E',
    appId: '1:969353545665:android:a3db7ef85b5b57f198d140',
    messagingSenderId: '969353545665',
    projectId: 'a18s-app',
    storageBucket: 'a18s-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj5ekEPnhH3U4R4sjebsABRMXYtOOqcA0',
    appId: '1:969353545665:ios:5cab5708ad62648498d140',
    messagingSenderId: '969353545665',
    projectId: 'a18s-app',
    storageBucket: 'a18s-app.appspot.com',
    iosClientId: '969353545665-78434s5sbv50kp3q848pp1aodfnvugps.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminStatAutos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj5ekEPnhH3U4R4sjebsABRMXYtOOqcA0',
    appId: '1:969353545665:ios:5cab5708ad62648498d140',
    messagingSenderId: '969353545665',
    projectId: 'a18s-app',
    storageBucket: 'a18s-app.appspot.com',
    iosClientId: '969353545665-78434s5sbv50kp3q848pp1aodfnvugps.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminStatAutos',
  );
}
